// import traps from "../../public/images/for_muscles_chart/traps.png";
// import triceps from "../../public/images/for_muscles_chart/triceps.png";
// import sholders from "../../public/images/for_muscles_chart/sholders.png";
// import grip from "../../public/images/for_muscles_chart/grip.png";
// import back from "../../public/images/for_muscles_chart/back_muscles.png";
// import chest from "../../public/images/for_muscles_chart/chest.png";
// import biceps from "../../public/images/for_muscles_chart/biceps.png";
// import abs from "../../public/images/for_muscles_chart/abs.png";
// import glutes from "../../public/images/for_muscles_chart/glutes.png";
// import hamstrings from "../../public/images/for_muscles_chart/hamstrings.png";
// import quads from "../../public/images/for_muscles_chart/quads.png";
// import calf_muscles from "../../public/images/for_muscles_chart/calf_muscles.png";
import { Muscle } from "@/types/Muscle";

const musclesList: Muscle[] = [
	{
		id: 1,
		n: "Traps",
		sn: "Trapezius",
		rel: ["Deltoids", "Rhomboids", "Lats"],
		func: "Supports scapular movement, neck stability, and posture.",
		anat: "A large triangular muscle extending from the base of the skull to the middle of the back.",
        img: "",
        desc: "The trapezius is a key muscle for upper body movement and posture, aiding in scapular elevation, retraction, and rotation.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Shrug.gif",
				n: "Barbell Shrug",
				diff: "Beginner",
				eq: "Barbell",
				tgt: "Trapezius",
				desc: "Lift the barbell by shrugging your shoulders upward, keeping arms straight.",
				s: 3,
				r: 12,
				tips: "Avoid rolling your shoulders. Focus on squeezing at the top.",
				vid: "https://www.youtube.com/watch?v=NAqCVe2mwzM",
			},
			{
				img: "https://www.dmoose.com/cdn/shop/articles/1_8db57df7-b8f2-412e-a364-745224090211.jpg?v=1647872727",
				n: "Dumbbell Upright Row",
				diff: "Intermediate",
				eq: "Dumbbells",
				tgt: "Trapezius",
				desc: "Pull dumbbells upward along your body to chest height, elbows out.",
				s: 3,
				r: 10,
				tips: "Keep wrists straight and don't use excessive weight.",
				vid: "https://www.youtube.com/watch?v=amCU-ziHITM",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 2,
		n: "Shoulders",
		sn: "Deltoids",
		rel: ["Traps", "Pecs", "Biceps"],
		func: "Facilitates arm abduction, flexion, and rotation.",
		anat: "A rounded muscle forming the contour of the shoulder.",
        img: "",
        desc: "The deltoid muscles are essential for arm movement and shoulder stability, playing a key role in overhead activities.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/07/Barbell-Standing-Military-Press.gif",
				n: "Overhead Press",
				diff: "Intermediate",
				eq: "Barbell",
				tgt: "Deltoids",
				desc: "Press the barbell overhead from shoulder height, fully extending arms.",
				s: 4,
				r: 8,
				tips: "Keep your core tight and avoid arching your back.",
				vid: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif",
				n: "Lateral Raise",
				diff: "Beginner",
				eq: "Dumbbells",
				tgt: "Deltoids",
				desc: "Raise dumbbells to the sides until arms are parallel to the floor.",
				s: 3,
				r: 12,
				tips: "Use light weight and control the movement.",
				vid: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
			},
		],
		inj: [
			{
				n: "Rotator Cuff Injury",
				desc: "Damage to the muscles or tendons around the shoulder joint, often from overhead movements.",
				prev: "Strengthen rotator cuff muscles, avoid excessive overhead lifting, and use proper form.",
			},
			{
				n: "Impingement Syndrome",
				desc: "Compression of shoulder tendons or bursa, causing pain and limited movement.",
				prev: "Maintain good posture, strengthen shoulder stabilizers, and avoid repetitive overhead activity.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 3,
		n: "Back muscles",
		sn: "Lats",
		rel: ["Traps", "Rhomboids", "Erector Spinae"],
		func: "Supports posture, pulls the arms downward and backward.",
		anat: "A large, flat muscle covering the lower and middle back.",
        img: "",
        desc: "The back muscles include the lats, rhomboids, and traps, which work together to support posture, pull movements, and spinal stability. They are crucial for pulling exercises like rows and pull-ups.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif",
				n: "Pull-Up",
				diff: "Intermediate",
				eq: "Pull-up Bar",
				tgt: "Lats",
				desc: "Pull your chin above the bar using your back and arms.",
				s: 3,
				r: 8,
				tips: "Use full range of motion and avoid swinging.",
				vid: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif",
				n: "Seated Row",
				diff: "Beginner",
				eq: "Cable Machine",
				tgt: "Rhomboids",
				desc: "Pull the handle toward your torso, squeezing your shoulder blades together.",
				s: 3,
				r: 10,
				tips: "Keep your back straight and don't lean back.",
				vid: "https://www.youtube.com/watch?v=GZbfZ033f74",
			},
		],
		inj: [
			{
				n: "Muscle Spasms",
				desc: "Involuntary contractions of back muscles, often due to fatigue or overuse.",
				prev: "Stay hydrated, stretch regularly, and avoid overexertion.",
			},
			{
				n: "Herniated Disc",
				desc: "A spinal disc bulges out and presses on nerves, causing pain or numbness.",
				prev: "Use proper lifting technique, strengthen core, and avoid sudden twisting.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 4,
		n: "Triceps",
		sn: "Triceps Brachii",
		rel: ["Deltoids", "Pecs", "Biceps"],
		func: "Extends the elbow joint.",
		anat: "A three-headed muscle located on the back of the upper arm.",
        img: "",
        desc: "Located on the back of the upper arm, the triceps are responsible for elbow extension. They are heavily involved in pushing movements like bench presses and dips.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bench-Dips.gif",
				n: "Tricep Dips",
				diff: "Beginner",
				eq: "Dip Bar",
				tgt: "Triceps",
				desc: "Lower your body by bending your elbows, then push back up.",
				s: 3,
				r: 10,
				tips: "Keep your elbows close to your body.",
				vid: "https://www.youtube.com/watch?v=0326dy_-CzM",
			},
			{
				img: "https://www.fitfatherproject.com/wp-content/uploads/2019/08/Skull-Crusher-exercise-long-image.jpg",
				n: "Skull Crushers",
				diff: "Intermediate",
				eq: "EZ Bar",
				tgt: "Triceps",
				desc: "Lie on a bench and lower the EZ bar to your forehead, then extend back up.",
				s: 3,
				r: 10,
				tips: "Keep your upper arms stationary.",
				vid: "https://www.youtube.com/watch?v=d_KZxkY_0cM",
			},
		],
		inj: [
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 5,
		n: "Glutes",
		sn: "Gluteus Maximus",
		rel: ["Hamstrings", "Quads", "Lower Back"],
		func: "Extends and rotates the hip joint.",
		anat: "The largest muscle in the body, located in the buttocks.",
        img: "",
        desc: "The glutes are the largest muscles in the body, located in the buttocks. They are essential for hip extension, rotation, and stabilization during walking, running, and squatting.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/BARBELL-SQUAT.gif",
				n: "Squats",
				diff: "Beginner",
				eq: "Bodyweight",
				tgt: "Glutes",
				desc: "Lower your body as if sitting back into a chair, then return to standing.",
				s: 3,
				r: 15,
				tips: "Keep your chest up and knees over your toes.",
				vid: "https://www.youtube.com/watch?v=aclHkVaku9U",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif",
				n: "Hip Thrust",
				diff: "Intermediate",
				eq: "Barbell",
				tgt: "Glutes",
				desc: "With your upper back on a bench, roll a barbell over your hips and thrust upward.",
				s: 3,
				r: 12,
				tips: "Squeeze your glutes at the top of the movement.",
				vid: "https://www.youtube.com/watch?v=Zp26q4BY5HE",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 6,
		n: "Hamstrings",
		sn: "Hamstrings",
		rel: ["Glutes", "Quads", "Calves"],
		func: "Flexes the knee and extends the hip.",
		anat: "A group of three muscles located on the back of the thigh.",
        img: "",
        desc: "The hamstrings are a group of muscles on the back of the thigh. They are responsible for knee flexion and hip extension, playing a key role in running, jumping, and bending movements.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif",
				n: "Deadlift",
				diff: "Intermediate",
				eq: "Barbell",
				tgt: "Hamstrings",
				desc: "Lift a barbell from the ground to hip level, keeping your back straight.",
				s: 3,
				r: 10,
				tips: "Engage your core and don't round your back.",
				vid: "https://www.youtube.com/watch?v=1ZXobu7JvvE",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/08/Seated-Leg-Curl.gif",
				n: "Leg Curl",
				diff: "Beginner",
				eq: "Leg Curl Machine",
				tgt: "Hamstrings",
				desc: "Curl your legs towards your buttocks while lying face down.",
				s: 3,
				r: 12,
				tips: "Adjust the machine to fit your leg length.",
				vid: "https://www.youtube.com/watch?v=ELOCsoDSmrg",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 7,
		n: "Calves",
		sn: "Gastrocnemius",
		rel: ["Hamstrings", "Quads", "Ankles"],
		func: "Plantar flexes the foot and stabilizes the ankle.",
		anat: "A pair of muscles located on the back of the lower leg.",
        img: "",
        desc: "The calf muscles are located on the back of the lower leg. They are responsible for plantar flexion (pointing the toes) and are essential for walking, running, and jumping.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif",
				n: "Calf Raise",
				diff: "Beginner",
				eq: "Bodyweight",
				tgt: "Calves",
				desc: "Stand on the balls of your feet and raise your heels off the ground.",
				s: 3,
				r: 15,
				tips: "Keep your knees straight and don't bounce.",
				vid: "https://www.youtube.com/watch?v=-M4-G8p8fmc",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/09/Barbell-Seated-Calf-Raise.gif",
				n: "Seated Calf Raise",
				diff: "Intermediate",
				eq: "Calf Raise Machine",
				tgt: "Calves",
				desc: "Sit on the machine and place the balls of your feet on the platform, then raise your heels.",
				s: 3,
				r: 12,
				tips: "Adjust the machine to your height and use a full range of motion.",
				vid: "https://www.youtube.com/watch?v=JbyjNymZOt0",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 8,
		n: "Chest",
		sn: "Pectoralis Major",
		rel: ["Deltoids", "Triceps", "Biceps"],
		func: "Adducts and flexes the arm at the shoulder joint.",
		anat: "A large, fan-shaped muscle covering the chest.",
        img: "",
        desc: "The chest muscles are located on the front of the upper body. They are responsible for pushing movements, arm adduction, and shoulder flexion, making them key for exercises like push-ups and bench presses.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif",
				n: "Bench Press",
				diff: "Intermediate",
				eq: "Barbell",
				tgt: "Pectoralis Major",
				desc: "Lie on a bench and press the barbell up from chest level.",
				s: 3,
				r: 10,
				tips: "Keep your feet flat on the ground and don't arch your back.",
				vid: "https://www.youtube.com/watch?v=gRVjAtPip0Y",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Push-Up.gif",
				n: "Push-Up",
				diff: "Beginner",
				eq: "Bodyweight",
				tgt: "Pectoralis Major",
				desc: "Lower your body to the ground and push back up, keeping your body straight.",
				s: 3,
				r: 15,
				tips: "Keep your elbows at a 45-degree angle to your body.",
				vid: "https://www.youtube.com/watch?v=IODxDxX7oi4",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 9,
		n: "Biceps",
		sn: "Biceps Brachii",
		rel: ["Triceps", "Forearms", "Deltoids"],
		func: "Flexes the elbow and supinates the forearm.",
		anat: "A two-headed muscle located on the front of the upper arm.",
        img: "",
        desc: "The biceps are located on the front of the upper arm. They are responsible for elbow flexion and forearm supination, playing a key role in pulling movements like curls and rows.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif",
				n: "Bicep Curl",
				diff: "Beginner",
				eq: "Dumbbells",
				tgt: "Biceps Brachii",
				desc: "Curl the dumbbells up towards your shoulders, keeping your elbows close to your body.",
				s: 3,
				r: 12,
				tips: "Don't swing your body; keep the movement controlled.",
				vid: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif",
				n: "Hammer Curl",
				diff: "Intermediate",
				eq: "Dumbbells",
				tgt: "Biceps Brachii",
				desc: "Curl the dumbbells with palms facing each other, lifting towards your shoulders.",
				s: 3,
				r: 10,
				tips: "Keep your elbows stationary and focus on your biceps.",
				vid: "https://www.youtube.com/watch?v=TwD-YGVP4Bk",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 10,
		n: "Abs",
		sn: "Abdominals",
		rel: ["Obliques", "Lower Back", "Hip Flexors"],
		func: "Flexes and rotates the trunk; stabilizes the core.",
		anat: "A group of muscles located in the front of the torso.",
        img: "",
        desc: "The abdominal muscles are located in the front of the torso. They are responsible for trunk flexion, rotation, and stabilization, making them essential for core strength and posture.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/plank.gif",
				n: "Plank",
				diff: "Beginner",
				eq: "Bodyweight",
				tgt: "Abdominals",
				desc: "Hold your body in a straight line from head to heels, resting on your forearms and toes.",
				s: 3,
				r: 30,
				tips: "Keep your body straight and don't let your hips sag.",
				vid: "https://www.youtube.com/watch?v=pSHjTRCQxIw",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Russian-Twist.gif",
				n: "Russian Twist",
				diff: "Intermediate",
				eq: "Medicine Ball",
				tgt: "Obliques",
				desc: "Sit on the ground with your knees bent, lean back slightly, and twist your torso to touch the ground beside you.",
				s: 3,
				r: 15,
				tips: "Keep your core engaged and don't rush the movement.",
				vid: "https://www.youtube.com/watch?v=wkD8rjkodUI",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 11,
		n: "Grip",
		sn: "Forearm Muscles",
		rel: ["Biceps", "Triceps", "Shoulders"],
		func: "Controls grip strength and wrist movement.",
		anat: "A group of muscles located in the forearm.",
        img: "",
        desc: "The forearm muscles control grip strength and wrist movement. They are essential for holding, lifting, and pulling exercises, as well as improving overall hand strength.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Dumbbell-Seated-Neutral-Wrist-Curl.gif",
				n: "Wrist Curl",
				diff: "Beginner",
				eq: "Dumbbells",
				tgt: "Forearm Muscles",
				desc: "Sit and rest your forearms on your thighs, curl the dumbbells up using only your wrists.",
				s: 3,
				r: 15,
				tips: "Keep the movement slow and controlled.",
				vid: "https://www.youtube.com/watch?v=qMtmHwaCmYI",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Barbell-Reverse-Wrist-Curl.gif",
				n: "Reverse Wrist Curl",
				diff: "Intermediate",
				eq: "Dumbbells",
				tgt: "Forearm Muscles",
				desc: "Sit and rest your forearms on your thighs, palms down, curl the dumbbells up using only your wrists.",
				s: 3,
				r: 15,
				tips: "Focus on the contraction at the top of the movement.",
				vid: "https://www.youtube.com/watch?v=GZbfZ033f74",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
	{
		id: 12,
		n: "Quads",
		sn: "Quadriceps",
		rel: ["Hamstrings", "Glutes", "Calves"],
		func: "Extends the knee and flexes the hip.",
		anat: "A group of four muscles located on the front of the thigh.",
        img: "",
        desc: "The quadriceps are a group of muscles on the front of the thigh. They are responsible for knee extension and hip flexion, playing a key role in walking, running, and squatting.",
		ex: [
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2015/11/Leg-Press.gif",
				n: "Leg Press",
				diff: "Beginner",
				eq: "Leg Press Machine",
				tgt: "Quadriceps",
				desc: "Sit on the machine and press the platform away using your legs.",
				s: 3,
				r: 10,
				tips: "Don't lock your knees at the top of the movement.",
				vid: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
			},
			{
				img: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lunge.gif",
				n: "Lunges",
				diff: "Intermediate",
				eq: "Bodyweight",
				tgt: "Quadriceps",
				desc: "Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle.",
				s: 3,
				r: 12,
				tips: "Keep your front knee over your ankle and don't let it cave in.",
				vid: "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
			},
		],
		inj: [
			{
				n: "Strain",
				desc: "Overstretching or tearing of muscle fibers, often due to excessive load or improper form.",
				prev: "Warm up properly, use correct technique, and avoid lifting too heavy.",
			},
			{
				n: "Tendinitis",
				desc: "Inflammation of the tendon, usually from repetitive movements or overuse.",
				prev: "Allow adequate rest, avoid repetitive strain, and strengthen supporting muscles.",
			},
		],
		str: [
			{
				n: "Static Stretch",
				desc: "Hold a static stretch targeting this muscle group.",
				dur: "30s",
			},
			{
				n: "Dynamic Stretch",
				desc: "Perform slow, controlled movements through the muscle's range of motion.",
				dur: "30s",
			},
		],
		freq: { b: "1-2", i: "2-3", a: "3-4" },
	},
];

export default musclesList;